import { Heart, Flower2, Sparkles, MessageCircle, Check, ArrowUpRight } from 'lucide-react';
import { WhatsAppButton } from './WhatsAppButton';
import { Brand, links } from './Header';
import { whatsappUrl } from '../utils/whatsapp';
export function About(){return <section id="sobre" className="about section-space"><div className="container about-layout"><div className="about-image"><img src="/images/marca.webp" alt="Arte original da Selma Artes em Detalhes: crochê, flores e sandálias decoradas" width="800" height="800" loading="lazy"/><span className="about-tag"><Heart size={18}/> Nossa essência, em cada detalhe</span></div><div className="about-copy"><p className="eyebrow">CONHEÇA A SELMA ARTES EM DETALHES</p><h2>Feito à mão,<br/>feito com <em>carinho.</em></h2><p>Na Selma Artes em Detalhes, cada trabalho recebe atenção especial. São peças artesanais produzidas com cuidado, criatividade e capricho para transformar ambientes e tornar presentes ainda mais especiais.</p><p>Do crochê à decoração com pedraria e miçangas em sandálias, o encanto está nos detalhes.</p><div className="about-points">{['Qualidade e capricho','Peças artesanais','Personalizações sob encomenda','Atendimento próximo'].map(t=><span key={t}><Check size={17}/>{t}</span>)}</div><a href="#encomendas" className="text-link">Vamos criar algo especial? <ArrowUpRight size={18}/></a></div></div></section>}
export function CustomOrders(){return <section id="encomendas" className="custom-section"><div className="container custom-panel"><Flower2 className="custom-flower" size={160} strokeWidth={.65}/><div><p className="eyebrow">DO SEU JEITO, COM NOSSO CARINHO</p><h2>Quer uma peça do seu jeito?</h2><p>A Selma também faz peças por encomenda. Entre em contato para consultar possibilidades de cores, detalhes e personalizações.</p><WhatsAppButton message="Olá, Selma! Gostaria de conversar sobre uma peça personalizada." className="button-light">Pedir orçamento pelo WhatsApp</WhatsAppButton></div><div className="custom-detail"><span>01</span><p>Conte sua ideia</p><span>02</span><p>Converse sobre os detalhes</p><span>03</span><p>Consulte seu orçamento</p></div></div></section>}
export function Benefits(){return <section className="benefits section-space" aria-label="O cuidado por trás das peças"><div className="container benefits-grid">{[{Icon:Heart,title:'Feito à mão',text:'Cada peça recebe atenção aos detalhes.'},{Icon:Flower2,title:'Personalizações',text:'Consulte opções feitas especialmente para você.'},{Icon:Sparkles,title:'Qualidade e capricho',text:'Artesanato produzido com cuidado.'},{Icon:MessageCircle,title:'Atendimento com carinho',text:'Converse diretamente com a Selma pelo WhatsApp.'}].map(({Icon,title,text})=><div className="benefit" key={title}><Icon size={29} strokeWidth={1.2}/><h3>{title}</h3><p>{text}</p></div>)}</div></section>}
export function FinalCTA(){return <section id="contato" className="final-cta"><div className="container"><Heart size={30} strokeWidth={1.2}/><h2>Encontrou algo que<br/>combina com você?</h2><p>Fale diretamente com a Selma e consulte disponibilidade, cores e encomendas.</p><WhatsAppButton>Conversar no WhatsApp</WhatsAppButton><a className="contact-number" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">(61) 99821-9571</a></div></section>}
export function Footer(){return <footer><div className="container footer-top"><div><Brand/><p>Crochê e muito mais...</p></div><nav aria-label="Navegação do rodapé">{links.slice(1).map(([label,id])=><a href={`#${id}`} key={id}>{label}</a>)}</nav><a className="footer-contact" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">Atendimento pelo WhatsApp<strong>(61) 99821-9571 ↗</strong></a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Selma Artes em Detalhes</span><span className="developer-credit">Feito por Pedro Leite Campos <a href="tel:+5561992866000" aria-label="Contato de Pedro Leite Campos: (61) 99286-6000">Contato: (61) 99286-6000</a></span></div></footer>}
